# Generated by Django 4.2.9 on 2024-02-14 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('image', models.ImageField(blank=True, null=True, upload_to='company_images')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_schedule', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_job', models.CharField(max_length=256)),
                ('experience', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=256)),
                ('salary', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse_job.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse_job.company')),
                ('gender', models.ForeignKey(default='Нет', on_delete=django.db.models.deletion.SET_DEFAULT, to='browse_job.gender')),
                ('work_schedule_job', models.ForeignKey(default='Нет', on_delete=django.db.models.deletion.SET_DEFAULT, to='browse_job.workschedule')),
            ],
        ),
    ]
